name: Build and Deploy
on:
  push:
    branches:
      - v2.0-react
  pull_request:
    branches:
      - v2.0-react
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    permissions: write-all
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Setup Node 🛠️
        uses: actions/setup-node@v1
        with:
          node-version: "19.1.0"
      - name: Install Dependencies 🔧
        run: |
          npm install
      - name: Build 🏗️
        run: |
          npm run build
      - name: Deploy 🚀
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
